//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementText
    {
        public AgreementText()
        {
            this.Companies = new HashSet<Company>();
            this.Settings = new HashSet<Setting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Setting> Settings { get; set; }
    }
}
