//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public Agreement()
        {
            this.Logins = new HashSet<Login>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string Code { get; set; }
        public int ClientId { get; set; }
        public int CompanyId { get; set; }
        public int LocationId { get; set; }
        public int ServiceTypeId { get; set; }
        public System.DateTime DateConclusion { get; set; }
        public string Description { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
        public virtual Location Location { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
    }
}
