//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditSetting
    {
        public int Id { get; set; }
        public bool TrackClientsSessionStart { get; set; }
        public bool TrackClientsSessionEnd { get; set; }
        public bool TrackTryToEnterToInvestorOffice { get; set; }
        public bool TrackErrors { get; set; }
        public bool TrackDefaultPageRequest { get; set; }
        public bool TrackPortfolioReturnReport { get; set; }
        public bool TrackDoubleSideCommunicationMessageTypeSet { get; set; }
        public bool TrackDoubleSideCommunicationPerformerGroupSet { get; set; }
        public bool TrackDoubleSideCommunicationResponsibleSet { get; set; }
        public bool TrackDoubleSideCommunicationReplies { get; set; }
        public bool TrackDoubleSideCommunicationGradeSet { get; set; }
        public bool TrackTryToOpenForbiddenPage { get; set; }
    }
}
