//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public short AuditEntryTypeId { get; set; }
        public string AuditEntryTypeName { get; set; }
        public string Login { get; set; }
        public string ClientFullName { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<bool> IsTimeout { get; set; }
        public string StackTrace { get; set; }
        public Nullable<int> DoubleSideCommunicationMessageChainId { get; set; }
        public string DoubleSideCommunicationMessageChainName { get; set; }
        public string Portfolio { get; set; }
        public Nullable<double> PortfolioReturn { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTill { get; set; }
    }
}
