//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AxiomusRegionRequestsArea
    {
        public int Id { get; set; }
        public int AxiomusRegionRequestsRegionId { get; set; }
        public string Name { get; set; }
        public Nullable<double> DeliveryPrice { get; set; }
    
        public virtual AxiomusRegionRequestsRegion AxiomusRegionRequestsRegion { get; set; }
    }
}
