//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Agreements = new HashSet<Agreement>();
            this.Customers = new HashSet<Customer>();
            this.Logins = new HashSet<Login>();
            this.MailMessages = new HashSet<MailMessage>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.UserInfos = new HashSet<UserInfo>();
            this.Roles = new HashSet<Role>();
            this.NewsBlockMessages = new HashSet<NewsBlockMessage>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool NeedAssent { get; set; }
        public string ClientCode { get; set; }
        public string FullName { get; set; }
        public int PersonType { get; set; }
        public string MobilePhone { get; set; }
        public string RegistrationAddress { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string Series { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentIssuingAuthority { get; set; }
        public string AuthoritySubdivisionCode { get; set; }
        public Nullable<System.DateTime> IdentificationDocumentDateOfIssue { get; set; }
        public string FullCompanyName { get; set; }
        public string ShortCompanyName { get; set; }
        public string CertificateNumber { get; set; }
        public string CompanyRegisteringAuthority { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public string Ogrn { get; set; }
        public string OgrnAuthority { get; set; }
        public Nullable<System.DateTime> DateOfOgrn { get; set; }
        public string VkPageUrl { get; set; }
    
        public virtual ICollection<Agreement> Agreements { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<MailMessage> MailMessages { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<UserInfo> UserInfos { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<NewsBlockMessage> NewsBlockMessages { get; set; }
    }
}
