//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Agreements = new HashSet<Agreement>();
            this.CompanyServices = new HashSet<CompanyService>();
            this.Locations = new HashSet<Location>();
            this.NewsBlockMessageFilters = new HashSet<NewsBlockMessageFilter>();
        }
    
        public int Id { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public int CompanyType { get; set; }
        public string Description { get; set; }
        public string WebLink { get; set; }
        public string Contacts { get; set; }
        public string Theme { get; set; }
        public string ExternalCode { get; set; }
        public Nullable<int> AgreementTextId { get; set; }
    
        public virtual ICollection<Agreement> Agreements { get; set; }
        public virtual AgreementText AgreementText { get; set; }
        public virtual ICollection<CompanyService> CompanyServices { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<NewsBlockMessageFilter> NewsBlockMessageFilters { get; set; }
    }
}
