//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmSource
    {
        public CrmSource()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public int ShopId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
