//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string VkName { get; set; }
        public string VkLink { get; set; }
        public string VkId { get; set; }
        public string PhotoLink { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Contacts { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> FirstContact { get; set; }
        public Nullable<System.DateTime> LastContact { get; set; }
        public Nullable<System.DateTime> NextContact { get; set; }
        public int CrmStatus { get; set; }
        public string CrmComments { get; set; }
        public int ShopId { get; set; }
        public string CrmTags { get; set; }
        public string CrmWhyCancel { get; set; }
        public Nullable<int> CrmSourceId { get; set; }
        public Nullable<int> ManagerId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Client Client { get; set; }
        public virtual Country Country { get; set; }
        public virtual CrmSource CrmSource { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
