//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public Good()
        {
            this.GoodsMotions = new HashSet<GoodsMotion>();
            this.GoodsPositions = new HashSet<GoodsPosition>();
            this.GoodsSizes = new HashSet<GoodsSize>();
        }
    
        public int Id { get; set; }
        public int GoodsCategoryId { get; set; }
        public int GoodsTypeId { get; set; }
        public string Marking { get; set; }
        public string Name { get; set; }
        public string PhotoLink { get; set; }
        public string PhotoPageLink { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public Nullable<double> Weight { get; set; }
        public int ShopId { get; set; }
        public string ShopPageLink { get; set; }
    
        public virtual GoodsCategory GoodsCategory { get; set; }
        public virtual GoodsType GoodsType { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual ICollection<GoodsMotion> GoodsMotions { get; set; }
        public virtual ICollection<GoodsPosition> GoodsPositions { get; set; }
        public virtual ICollection<GoodsSize> GoodsSizes { get; set; }
    }
}
