//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public Invitation()
        {
            this.InvitationRoles = new HashSet<InvitationRole>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Email { get; set; }
        public int InvitedByLoginId { get; set; }
        public Nullable<int> CreatedLoginId { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
    
        public virtual ICollection<InvitationRole> InvitationRoles { get; set; }
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
    }
}
