//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Agreements = new HashSet<Agreement>();
            this.UserInfoItems = new HashSet<UserInfoItem>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public int LocationTypeId { get; set; }
        public int CompanyId { get; set; }
        public string Contacts { get; set; }
    
        public virtual ICollection<Agreement> Agreements { get; set; }
        public virtual Company Company { get; set; }
        public virtual LocationType LocationType { get; set; }
        public virtual ICollection<UserInfoItem> UserInfoItems { get; set; }
    }
}
