//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.Invitations = new HashSet<Invitation>();
            this.Invitations1 = new HashSet<Invitation>();
            this.MailMessages = new HashSet<MailMessage>();
            this.MailMessages1 = new HashSet<MailMessage>();
            this.MessageChainMessages = new HashSet<MessageChainMessage>();
            this.MessageChains = new HashSet<MessageChain>();
            this.MessageChains1 = new HashSet<MessageChain>();
            this.MailMessages2 = new HashSet<MailMessage>();
            this.MessageChainMessages1 = new HashSet<MessageChainMessage>();
            this.MessageChains2 = new HashSet<MessageChain>();
            this.NewsBlockMessageFilters = new HashSet<NewsBlockMessageFilter>();
        }
    
        public int Id { get; set; }
        public string Login1 { get; set; }
        public string Password { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> AgreementId { get; set; }
        public bool AskNewPassword { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public bool IsOnline { get; set; }
        public Nullable<int> ShopId { get; set; }
        public bool AskToProvideNewLogin { get; set; }
        public bool Blocked { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<Invitation> Invitations1 { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual ICollection<MailMessage> MailMessages { get; set; }
        public virtual ICollection<MailMessage> MailMessages1 { get; set; }
        public virtual ICollection<MessageChainMessage> MessageChainMessages { get; set; }
        public virtual ICollection<MessageChain> MessageChains { get; set; }
        public virtual ICollection<MessageChain> MessageChains1 { get; set; }
        public virtual ICollection<MailMessage> MailMessages2 { get; set; }
        public virtual ICollection<MessageChainMessage> MessageChainMessages1 { get; set; }
        public virtual ICollection<MessageChain> MessageChains2 { get; set; }
        public virtual ICollection<NewsBlockMessageFilter> NewsBlockMessageFilters { get; set; }
    }
}
