//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailMessage
    {
        public MailMessage()
        {
            this.MailMessageFiles = new HashSet<MailMessageFile>();
            this.Logins = new HashSet<Login>();
        }
    
        public int Id { get; set; }
        public int MailMessageId { get; set; }
        public int MailMessageChainId { get; set; }
        public int OwnerLoginId { get; set; }
        public int OwnerClientId { get; set; }
        public int FromLoginId { get; set; }
        public bool IsRead { get; set; }
        public bool IsChatInvite { get; set; }
        public System.DateTime Date { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
        public virtual ICollection<MailMessageFile> MailMessageFiles { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
    }
}
