//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageChainMessage
    {
        public MessageChainMessage()
        {
            this.Files = new HashSet<File>();
            this.Logins = new HashSet<Login>();
        }
    
        public int Id { get; set; }
        public int MessageChainId { get; set; }
        public int AuthorLoginId { get; set; }
        public System.DateTime Date { get; set; }
        public string Text { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual MessageChain MessageChain { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
    }
}
