//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageChain
    {
        public MessageChain()
        {
            this.MessageChainMessages = new HashSet<MessageChainMessage>();
            this.Roles = new HashSet<Role>();
            this.Logins = new HashSet<Login>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int AuthorLoginId { get; set; }
        public Nullable<int> ResponsibleLoginId { get; set; }
        public Nullable<int> MessageTypeId { get; set; }
        public Nullable<int> CompanyServiceId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> LastMessageDate { get; set; }
        public Nullable<bool> IsSatisfied { get; set; }
    
        public virtual CompanyService CompanyService { get; set; }
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
        public virtual ICollection<MessageChainMessage> MessageChainMessages { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
    }
}
