//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsBlockMessage
    {
        public NewsBlockMessage()
        {
            this.NewsBlockMessageFiles = new HashSet<NewsBlockMessageFile>();
            this.NewsBlockMessageFilters = new HashSet<NewsBlockMessageFilter>();
            this.Clients = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public int NewsBlockId { get; set; }
    
        public virtual NewsBlock NewsBlock { get; set; }
        public virtual ICollection<NewsBlockMessageFile> NewsBlockMessageFiles { get; set; }
        public virtual ICollection<NewsBlockMessageFilter> NewsBlockMessageFilters { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
    }
}
