//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsBlockMessageFile
    {
        public int NewsBlockMessageId { get; set; }
        public int Id { get; set; }
        public string OriginalName { get; set; }
        public string FilePath { get; set; }
        public string MimeType { get; set; }
        public int FileLocationId { get; set; }
        public bool AllowToZip { get; set; }
    
        public virtual NewsBlockMessage NewsBlockMessage { get; set; }
    }
}
