//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsBlockMessageFilter
    {
        public NewsBlockMessageFilter()
        {
            this.Logins = new HashSet<Login>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NewsBlockMessageId { get; set; }
        public int FilterTypeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<int> NewsBlockId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual NewsBlock NewsBlock { get; set; }
        public virtual NewsBlockMessage NewsBlockMessage { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
    }
}
