//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsBlock
    {
        public NewsBlock()
        {
            this.NewsBlockMessages = new HashSet<NewsBlockMessage>();
            this.NewsBlockMessageFilters = new HashSet<NewsBlockMessageFilter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<NewsBlockMessage> NewsBlockMessages { get; set; }
        public virtual ICollection<NewsBlockMessageFilter> NewsBlockMessageFilters { get; set; }
    }
}
