//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string InvestmentCompanyName { get; set; }
        public string InvestorOfficeName { get; set; }
        public bool UseDbPositions { get; set; }
        public int NumberOfDaysToLookBack { get; set; }
        public bool UseRandomMarketData { get; set; }
        public bool UsePifTradeVolume { get; set; }
        public int CacheUpdateTime { get; set; }
        public bool UseAdvancedPageArguments { get; set; }
        public bool UsePositionsOnlyFromDb { get; set; }
        public int GridPageSize { get; set; }
        public bool GenerateRandomMarketData { get; set; }
        public int TimeOutPeriod { get; set; }
        public bool UseMultiLevelMenu { get; set; }
        public short NegativeFormatType { get; set; }
        public string NotificationEmail { get; set; }
        public short DatePickerMode { get; set; }
        public string Theme { get; set; }
        public bool UseBllCaches { get; set; }
        public int TopObjectsCount { get; set; }
        public bool ShowGreetings { get; set; }
        public bool GeneratePifsAssetFlows { get; set; }
        public int PifsPositionsSource { get; set; }
        public bool IsTestVersion { get; set; }
        public bool UseValuationCurrencySelection { get; set; }
        public bool IsAlor { get; set; }
        public bool EnableWebTrading { get; set; }
        public bool UseActiveMenuBehavior { get; set; }
        public Nullable<int> AgreementTextId { get; set; }
        public short SmsSenderTypeId { get; set; }
        public string SmsSenderLogin { get; set; }
        public string SmsSenderPassword { get; set; }
        public bool DeleteFixedReportWithFiles { get; set; }
        public bool AllowToConfirmFixedReportByClient { get; set; }
        public bool ShowFixedReportPreviewLink { get; set; }
        public int FixedReportPreviewType { get; set; }
        public long FixedReportConfirmationPasswordTTL { get; set; }
        public string InvestorOfficeNameGenitive { get; set; }
        public string InvestorOfficeNameAccusative { get; set; }
        public string SmsSenderName { get; set; }
        public int MaxAnalyticalReportsColumnsCount { get; set; }
        public int ChartsRendererMode { get; set; }
        public bool UseMarketDataProviderWithRandomCurrentPrices { get; set; }
        public int RandomCurrentPricesGenerationInterval { get; set; }
        public int RandomCurrentPricesGenerationIntervalRatio { get; set; }
        public bool ShowPortfolioReturnsLinks { get; set; }
        public bool ShowPortfolioValuesLinks { get; set; }
        public bool ShowCashFlowsLinks { get; set; }
        public int NumberOfPointsInChart { get; set; }
        public int TradingAccountDropDownListType { get; set; }
        public bool UsePifsAssetFlowsFromDbForCalculations { get; set; }
        public bool CalculatePositionsVolume { get; set; }
        public bool ShowSecuritiesFlowsLinks { get; set; }
        public int PositionGroupType { get; set; }
        public int AccruedInterestProviderMode { get; set; }
    
        public virtual AgreementText AgreementText { get; set; }
    }
}
