//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityFrameworkConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.Cities = new HashSet<City>();
            this.CrmSources = new HashSet<CrmSource>();
            this.Customers = new HashSet<Customer>();
            this.Goods = new HashSet<Good>();
            this.GoodsCategories = new HashSet<GoodsCategory>();
            this.GoodsTypes = new HashSet<GoodsType>();
            this.Logins = new HashSet<Login>();
            this.Phrases = new HashSet<Phras>();
            this.Warehouses = new HashSet<Warehouse>();
            this.Addons = new HashSet<Addon>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string VkGroupUrl { get; set; }
        public bool AskToProvideInfo { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<CrmSource> CrmSources { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Good> Goods { get; set; }
        public virtual ICollection<GoodsCategory> GoodsCategories { get; set; }
        public virtual ICollection<GoodsType> GoodsTypes { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<Phras> Phrases { get; set; }
        public virtual ICollection<Warehouse> Warehouses { get; set; }
        public virtual ICollection<Addon> Addons { get; set; }
    }
}
